version: "3.8"

services:
  app:
    build: .
    restart: on-failure
    ports:
    - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - redis

  db:
    image: mysql
    restart: always
    ports:
    - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1qaz2wsx
      - MYSQL_DATABASE=purchase_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
    - db_data:/var/lib/mysql

  rabbitmq:
    image: bitnami/rabbitmq:3.7
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: bitnami/redis:5.0.4
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6367:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  worker:
    build: .
    command: "poetry run celery -A app.services.tasks worker -B -l debug -Q clean_task-queue -c 1"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - app
      - rabbitmq
      - redis

  dashboard:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@rabbitmq/
      - FLOWER_PORT=8888
      - FLOWER_URL_PREFIX=/flower
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  db_data: