version: "3.8"

services:
  app:
    build: .
    restart: on-failure
    ports:
    - "8000:8000"
    environment:
      DB_CONNECTION: "mysql://root:password@localhost:3306/purchase_manager"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: purchase_manager
    volumes:
    - my-db:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: "poetry run celery -A app.main worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  flower:
    build: .
    command: "poetry run celery -A app.main flower --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - app
      - redis
      - celery_worker

volumes:
  my-db: